# Generated by Django 3.1.1 on 2020-09-14 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product title')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('size', models.CharField(max_length=255, verbose_name='Size')),
                ('display', models.CharField(max_length=255, verbose_name='Display type')),
                ('video', models.CharField(max_length=255, verbose_name='Video type')),
                ('memory', models.CharField(max_length=255, verbose_name='Memory type')),
                ('battery', models.CharField(max_length=255, verbose_name='Battery')),
                ('sd', models.BooleanField(default=False)),
                ('main_cam_resolution', models.CharField(max_length=255, verbose_name='Main cam rersolution')),
                ('front_cam_resolution', models.CharField(max_length=255, verbose_name='Front cam rersolution')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product title')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('size', models.CharField(max_length=255, verbose_name='Size')),
                ('display', models.CharField(max_length=255, verbose_name='Display type')),
                ('processor', models.CharField(max_length=255, verbose_name='Processor type')),
                ('video', models.CharField(max_length=255, verbose_name='Video type')),
                ('battery_life', models.CharField(max_length=255, verbose_name='Battery life')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
