# Generated by Django 3.1.1 on 2020-09-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notebook_smartphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='memory',
            field=models.CharField(default=0, max_length=255, verbose_name='Memory type'),
            preserve_default=False,
        ),
    ]
