# Generated by Django 3.1.1 on 2020-09-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200917_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='memory',
            field=models.CharField(max_length=255, null=True, verbose_name='Memory type'),
        ),
    ]
