# Generated by Django 3.1.1 on 2020-09-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200918_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='sd_memory_size',
            field=models.CharField(default=0, max_length=255, verbose_name='SD memory size'),
            preserve_default=False,
        ),
    ]
