# Generated by Django 3.1.1 on 2020-10-11 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201006_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address')),
                ('status', models.CharField(choices=[('new', 'Order new'), ('in_progress', 'Order in progress'), ('ready', 'Order ready'), ('completed', 'Order comleted')], default='new', max_length=128, verbose_name='Order status')),
                ('buying_type', models.CharField(choices=[('self', 'Self'), ('delivery', 'Delivery')], default='self', max_length=128, verbose_name='Order buying type')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Order comment')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Order created date')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Get order date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='main.customer', verbose_name='Customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_customer', to='main.Order', verbose_name='Customer`s orders'),
        ),
    ]
